VDD: 
  - VDD
  - VCC
  - VPWR
  - VPP
  - VPB
GND: 
  - GND
  - VSS
  - VGND
  - VNB
  - VBB
PMOS:
  - PMOS
  - PCH
  - PCH_MAC
  - P12
  - sky130_fd_pr__pfet_01v8
NMOS:
  - NMOS
  - NCH
  - NCH_MAC
  - N12
  - sky130_fd_pr__nfet_01v8_lvt